extends: default

rules:
  line-length:
    max: 80
    level: error

  comments:
    min-spaces-from-content: 1

  comments-indentation:
    level: error

  document-start:
    present: false

  truthy:
    allowed-values: ['true', 'false', 'on', 'off']
    check-keys: false

ignore: |
  charts/*/templates/
  config/
  dist/
  *.generated.yaml
  .pre-commit-config.yaml
  .github/workflows/
