# Test configuration for CRD installation with keep policy
crds:
  install: true
  keep: true

# Basic operator configuration for testing
replicaCount: 1

image:
  repository: cloudflare-dns-operator
  tag: "test"

serviceAccount:
  create: true

rbac:
  create: true

operator:
  logLevel: info
  leaderElection: true

cloudflare:
  email: "test@example.com"
  apiToken: "test-token"
