# Health checks test values
# This file is used for testing health check configuration in CI/CD

# Enable comprehensive health checks
healthChecks:
  enabled: true

  # Liveness probe with shorter delays for testing
  livenessProbe:
    httpGet:
      path: /healthz
      port: 8081
    initialDelaySeconds: 10
    periodSeconds: 15
    timeoutSeconds: 3
    failureThreshold: 2
    successThreshold: 1

  # Readiness probe with faster checks for testing
  readinessProbe:
    httpGet:
      path: /readyz
      port: 8081
    initialDelaySeconds: 3
    periodSeconds: 5
    timeoutSeconds: 3
    failureThreshold: 2
    successThreshold: 1

  # Startup probe with reduced failure threshold for testing
  startupProbe:
    httpGet:
      path: /healthz
      port: 8081
    initialDelaySeconds: 5
    periodSeconds: 5
    timeoutSeconds: 3
    failureThreshold: 15
    successThreshold: 1

# Enable profiling for testing (normally disabled in production)
profiling:
  enabled: true
  port: 6060

# Resource limits optimized for testing
resources:
  limits:
    cpu: 200m
    memory: 128Mi
  requests:
    cpu: 50m
    memory: 64Mi

# Test credentials (for CI only)
cloudflare:
  email: "health-test@example.com"
  apiToken: "health-test-token-placeholder"
