# Staging environment values for cloudflare-dns-operator.

image:
  repository: cloudflare-dns-operator
  tag: staging
  pullPolicy: Always

replicaCount: 1

resources:
  limits:
    cpu: 300m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 64Mi

# Staging cloudflare configuration
cloudflare:
  email: ""
  apiTokenSecretName: "cf-staging-creds" # pragma: allowlist secret
  apiTokenSecretKey: "api-token"  # pragma: allowlist secret

operator:
  logLevel: info
  leaderElection: true

# Enable monitoring
monitoring:
  serviceMonitor:
    enabled: true
    interval: 30s
    labels:
      environment: staging

# Network policies for staging
networkPolicy:
  enabled: true

# Security context for staging
securityContext:
  allowPrivilegeEscalation: false
  capabilities:
    drop:
      - ALL
  readOnlyRootFilesystem: true
  runAsNonRoot: true
  runAsUser: 65532

podSecurityContext:
  runAsNonRoot: true
  runAsUser: 65532
  fsGroup: 65532

# Staging SLO configuration (moderate targets)
slo:
  enabled: true
  targets:
    availability: 99.0    # Moderate availability target for staging
    successRate: 98.0     # Moderate success rate
    latencyP95: 45s       # More relaxed latency target
    latencyP99: 90s
    throughputMin: 5.0    # Lower throughput requirement

  errorBudget:
    windowDays: 14        # Shorter window for staging
    alertThresholds:
      warning: 0.6        # Less sensitive alerting
      critical: 0.85

  alerting:
    pageAlerts:
      enabled: false      # No paging in staging
    ticketAlerts:
      enabled: true
      severity: warning

  recordingRules:
    enabled: true
    labels:
      environment: staging

# Staging reliability configuration
reliability:
  enabled: true

  circuitBreaker:
    enabled: true
    name: cloudflare-api-staging
    maxRequests: 3
    interval: 60s
    timeout: 30s
    failureRateThreshold: 0.7    # Higher threshold for staging
    minimumRequests: 5

  retry:
    enabled: true
    maxAttempts: 3
    initialDelay: 1s
    maxDelay: 20s
    multiplier: 2.0
    jitter: true

  rateLimiter:
    enabled: true
    type: token_bucket
    requestsPerSecond: 6.0       # Moderate rate for staging
    burstSize: 10
    backoffStrategy: block

  metrics:
    enabled: true

# Staging environment configuration
config:
  enabled: true
  environment: staging

  operator:
    logLevel: info
    reconcileInterval: "2m"     # More frequent reconciliation

  cloudflare:
    apiTimeout: "20s"
    rateLimitRPS: 6
    retryAttempts: 3

# Staging logging (more verbose)
logging:
  enabled: true
  level: info
  format: json
  development: false
  sampling:
    enabled: true
    initial: 100
    thereafter: 100

# Enable tracing in staging
tracing:
  enabled: true
  serviceName: cloudflare-dns-operator-staging
  environment: staging
  sampling:
    type: trace_id_ratio
    ratio: 0.5              # Sample 50% of traces
