# This rule is not used by the project k8s-operator-cloudflare itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants full permissions ('*') over dns.cloudflare.io.
# This role is intended for users authorized to modify roles and bindings within the cluster,
# enabling them to delegate specific permissions to other users or groups as needed.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: k8s-operator-cloudflare
    app.kubernetes.io/managed-by: kustomize
  name: cloudflarerecord-admin-role
rules:
- apiGroups:
  - dns.cloudflare.io
  resources:
  - cloudflarerecords
  verbs:
  - '*'
- apiGroups:
  - dns.cloudflare.io
  resources:
  - cloudflarerecords/status
  verbs:
  - get
