---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - dns.cloudflare.io
  resources:
  - cloudflarerecords
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - dns.cloudflare.io
  resources:
  - cloudflarerecords/finalizers
  verbs:
  - update
- apiGroups:
  - dns.cloudflare.io
  resources:
  - cloudflarerecords/status
  verbs:
  - get
  - patch
  - update
