{{- if .Values.rbac.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "cloudflare-dns-operator.fullname" . }}
  labels:
    {{- include "cloudflare-dns-operator.labels" . | nindent 4 }}
rules:
  - apiGroups: [""]
    resources: ["services", "endpoints", "pods"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["extensions", "networking.k8s.io"]
    resources: ["ingresses"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["cloudflare.io"]
    resources: ["dnsrecords", "dnsrecords/status", "dnsrecords/finalizers"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["create", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "cloudflare-dns-operator.fullname" . }}
  labels:
    {{- include "cloudflare-dns-operator.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "cloudflare-dns-operator.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "cloudflare-dns-operator.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
{{- end }}
